### ISSUE TITLE
Add support for pointers

### ISSUE THREAD

**Issue by japajoe** [oskarirauta/propertycpp#1]
Really useful utility you made but I would like it even more if you would add support for pointers as well. Is this something you're willing to do?

**Comment by oskarirauta** [comment]
If I remember correctly I attempted that and finally came to conclusion that it can't be integrated to this- you might have better luck if you create propertycpp2 that supports **only** pointers..

Unfortunately for you, I am way too busy to do that, my motivation usually is my own need and I do not need such thing, also I don't see that much point in there, your mileage may vary, but usually this kind of stuff is used for simple datatypes such as string, int, bool... Those that can be outputted to stdout without adding anything - so, I am sorry. But best of luck..

**Comment by nwrkbiz** [comment]
@oskarirauta  @japajoe I liked the concept and tried to do an improved implementation: https://nwrkbiz.gitlab.io/-/cpp-design-patterns/-/jobs/6360255072/artifacts/build_doc/documentation/Property_8h.html

https://gitlab.com/nwrkbiz/cpp-design-patterns/-/blob/develop/include/patterns/Property.h?ref_type=heads

Do you have some feedback?

**Comment by oskarirauta** [comment]
Hmm.. This is a bit forgotten project, but glad that you took interest in it.

<h2><sub>Ideology behind this</sub></h2>

propertycpp is more or less a concept; idea came from Swift language (Apple), I liked that concept very much on Swift, dynamic variables - I have used it on some project, that I can't remember for the moment, propably something that I never created a repository for, some small utility for something not that meaningful purpose- but propably haven't used it since.

I still like it very much. Would love to see something like that natively on C++, but that most likely will *never* will happen; I re-call that there was some kind of ideology, where this didn't fit at all, why it wouldn't be there. It's very much working concept anyway. Ofcourse if this kind of stuff would end up in C++, it would have nothing to do with me and approach very much would propably be very different..

<h2><sub>Feedback</sub></h2>
Now that I'm here, I apologise, but I will need to rename this project to property_cpp for personal needs (I try to name all my repositories as something_cpp for clarify reason), so I hope you will find this with refreshed name.

You could make a PR for this, or if you are interested in further development, I am willing to change ownership of repository for you, I am not trying to make any name here or anywhere, my personal agenda is to share, there absolutely is no need to re-invent the wheel if I can help it - in my case, it already works perfectly and does not need anything else, but your mileage can vary and and even though I am not going to do anything for it; does not mean that no one else should be, all ideas of *any* improvement, are very willingly accepted - maybe I even use something that wasn't made by myself, that I couldn't personally think that necessary until I found out how useful it is :)

Your code looks very pretty and readable, and might work better than mine. On any improvements, forks or what ever; my name is not necessary to be mentioned at all and even providing a link forked code is completely optional. I also won't mind any license changes unless someone attempts to sell it, ofcourse if it is a part of someone's program then I wouldn't mind, just glad if any of my work is useful for someone, but in case that source is sold.. so sad :( - though I wouldn't do/say anything even if someone would. Life's too short.

<h2><sub>Epilogue</sub></h2>

Please, update example code and make a PR and let me know if you'd like to take over this repository :)
Looking forward to hear from you again.
I also invited you as a collaborator, so you propably will be able to approve your own PR - never added anyone as a collaborator, so it's my fault if settings are incorrect and permissions do not allow it, all that stuff on repository settings seemed ok by me with a quick review..

You can contact me also directly by e-mail if preferred/needed (on any matter)- my e-mail is not a secret, it's oskari.rauta@gmail.com

**Comment by nwrkbiz** [comment]
> propertycpp is more or less a concept; idea came from Swift language (Apple), I liked that concept very much on Swift, dynamic variables - I have used it on some project, that I can't remember for the moment, propably something that I never created a
repository for, some small utility for something not that meaningful purpose- but propably haven't used it since.

I know this concept from C# and think this little class is an easy way to do getters/setters in C++.

> You could make a PR for this, or if you are interested in further development. 

I will mainly work on and maintain the stuff here, of course, everything will stay MIT License: https://gitlab.com/nwrkbiz/cpp-design-patterns 
If you want to, I can backport the stuff into this repo

> On any improvements, forks or what ever; my name is not necessary to be mentioned at all and even providing a link forked code is completely optional.

I always cite my sources, also because sometimes I want to re-resarch stuff (:  see: https://gitlab.com/nwrkbiz/cpp-design-patterns/-/commit/c890d5a678e6b1d562cee9b23031099a8fbddaf5#0b3e33619677413fe8f879987c9e0357046fe604_89_95

> I also invited you as a collaborator.

Thanks for adding me as a collaborator, I feel honored!

**Comment by oskarirauta** [comment]
@nwrkbiz 

I would be very glad on that backport :)
You propably noticed; I made some minor changes to repository's structure, code remained exactly the same except for Makefile that I updated.

**Comment by oskarirauta** [comment]
Remember to -singoff your work, that way you will get to cite your work by your self :)
Or add your self to README or to source, or where ever..

**Comment by oskarirauta** [comment]
@nwrkbiz

Out of this topic; but..

Previous version of my json_cpp was merged to [SimpleJSON](https://github.com/oskarirauta/SimpleJSON) as branch main/v2 which is archived (no further development expectable).

Completely [new json_cpp](https://github.com/oskarirauta/json_cpp) is finally complete with API documentation as well. Writing documentation propably took longer than writing actual code code. New version has different kind of approach to use sub-class of std::variant instead of templating. Your name is mentioned on wiki.

**Comment by nwrkbiz** [comment]
>  Writing documentation propably took longer than writing actual code code.

Have you ever considered using doxygen? It is the de-facto standard for C and C++ and really eases the documentation process. Also most IDEs will provide hints based on the doxygen comments within the autocomplete context menus. Also you can introduce quality gates to enforce yourself to document all classes and functions.

**Comment by japajoe** [comment]
Just my two cents. I haven't used this code for a long time because I came to the realization that it does not fit in with how you'd typically do things in C++. If used in a personal project then sure it is fine, but in any other case it would be odd because it's not a language feature and doesn't adhere to C++ standards.

**Comment by nwrkbiz** [comment]
> Just my two cents. I haven't used this code for a long time because I came to the realization that it does not fit in with how you'd typically do things in C++. If used in a personal project then sure it is fine, but in any other case it would be odd because it's not a language feature and doesn't adhere to C++ standards.

Uff, how to do things best in C++ is a highly emotional topic :D But I would agree to not use this when designing user facing C++ apis!

**Comment by oskarirauta** [comment]
@nwrkbiz

Usually I don't write documents, my repositories are often very well distributed into sections; for example, I have a project that replaces lcd4linux (but for single driver only, at least on the moment; and supports only graphical displays), it takes advantage of my repositories, project is quite big- untrimmed binary with debug symbols is more than 20mb.. Anyway, point is that it uses quite many of my repositories- as they are so well distributed into sections that every single one is pretty small- for example, this property_cpp- really small. So most often, simple example program is best possible documentation of what can be done with it and how; there's old saying that one picture can describe more than thousand words..

But in this case, json_cpp also grew to quite big, has a lot of features even though they all are necessary, nothing too fancy there; well anyway, that many functions had to be documented, if not for anyone else, then for me, when I next need it after 5 years and have no memory of how to use it 😄 

But yeah, maybe I should some day consider checking out oxygen, my IDE though is editor called nano in several terminal window's, running a ssh connection to my linux host that I use..

And I agree with @japajoe - When I got this cooked up, I was very happy about it, but realised that it's not the way that things should be done on C++ and even while it works and is very nice- some people might be even angry for something like this to be used 😄 It isn't crime though.. Actually with that lcd2linux (my lcd4linux replacement), on one moment I thought that I'd might to use this.. But ended not to.

If either you are curious from your nature, and want to see something interesting, check out [expr_cpp](https://github.com/oskarirauta/expr_cpp) that I use in my lcd project. It mimics original expression language used in lcd4linux, does have all kinds of bells and whistles, having some more that lacked in original expression language, and lacking some.. It's fun. I originally tried to look something like it, but didn't find anything that I could had been able to use- most expression related libraries were more regex focused or lacked support for both, text and numbers.. Or were not extendable.. Still.. I have a feeling that it could be stronger..

If you test it, beware-
To do this:
`1 == 0 ? 9 : 5 + 1  + 3`
should be written like this:
`1 == 0 ? 9 : (5 + 1 + 3)`

Resolution always is 9.... But for calculus, it cannot understand that rest would be a single equation..
That library also is quite big, like json is.. But there's not too many functions out for it, so no need for extensive documentation ;) - just give it a string with your expression and check out of results :smile:
And for that example I gave- I am not sure, but I think, original expression library would had possibly been able to solve it without braces..

My luck though that it isn't popular or afaik, used by anyone else besides me; propably has quite a lot that could be better. I am happy with it though as it is, since it... works for me :smile:
